#!/bin/bash

# ============================================================================
# tools/cursor/adapt/agent-to-mode.sh — registry agent (.md) -> Cursor Custom
# Mode artifact (one file per agent)
# ============================================================================
# Ambiguity resolved (documented here per the task's request — see
# docs/AI-SETUP-PLAN-v2.md sections 5.1 and 2.2, and see how
# docs/RESTRUCTURE-2026-06.md and tools/claude/enable.sh leave rationale
# in-repo the same way):
#
#   Section 5.1's worked example capabilities.yaml has:
#     agents: { mechanism: custom-mode, path: ".cursor/modes.json" }
#   which implies ONE JSON file holding every mode.
#
#   Section 2.2's tier-B row says explicitly:
#     "agent-to-mode.sh renderiza el body completo a UN ARCHIVO POR AGENTE
#      en el formato nativo de esa tool — mismo contenido, invocación manual"
#   which implies N files, one per agent.
#
#   These two statements conflict and there was no web access available to
#   confirm Cursor's actual current on-disk Custom Mode format (if Custom
#   Modes are even configurable via a file Cursor reads automatically, vs.
#   only through the Settings UI). Given that, section 2.2 is treated as
#   authoritative here: it is the more detailed, explicit tier-B spec (full
#   paragraph describing the mechanism), while section 5.1 is just a
#   shorthand path stub in a worked example. So this script renders ONE
#   MARKDOWN FILE PER AGENT under .cursor/modes/<agent-name>.md — never a
#   single .cursor/modes.json — with the agent's FULL body preserved
#   verbatim (not condensed; condensing to a roster is tier C / Copilot,
#   handled by a later phase's lib/condense.mjs, not here). Each file is
#   human-readable and includes a short note on how to paste it into
#   Cursor's Settings -> Chat -> Custom Modes UI, since that is the only
#   Custom Mode configuration surface confirmed to exist without inventing
#   an unverified .json schema.
#
# No new dependencies — pure bash/grep/sed/awk (same style as rule-to-mdc.sh).
#
# Usage:
#   agent-to-mode.sh <registry-agent.md>          <output-dir>   # single file
#   agent-to-mode.sh <dir-of-registry-agents>     <output-dir>   # all *.md in dir
#
# Example:
#   tools/cursor/adapt/agent-to-mode.sh registry/agents .cursor/modes
# ============================================================================

set -e

usage() {
  echo "Usage: agent-to-mode.sh <registry-agent.md-or-dir> <output-dir>" >&2
  exit 1
}

[ $# -eq 2 ] || usage

SRC="$1"
OUT_DIR="$2"

mkdir -p "$OUT_DIR"

convert_one() {
  local src="$1"
  local out_dir="$2"
  local name description out_file

  name="$(basename "$src" .md)"
  out_file="$out_dir/$name.md"

  # description: from the frontmatter block (between the first two "---" lines).
  description="$(awk '/^---$/{n++; next} n==1' "$src" | grep '^description:' | sed 's/^description:[[:space:]]*//')"
  if [ -z "$description" ]; then
    echo "agent-to-mode.sh: no 'description:' key found in frontmatter of $src" >&2
    exit 1
  fi

  {
    echo "# Cursor Custom Mode — $name"
    echo ""
    echo "> Generated by tools/cursor/adapt/agent-to-mode.sh from registry/agents/$name.md"
    echo "> Tier B (docs/AI-SETUP-PLAN-v2.md section 2.2): full agent content preserved, invocation is manual."
    echo "> To use: Cursor -> Settings -> Chat -> Custom Modes -> New Mode -> Name: \"$name\" -> paste"
    echo "> everything under \"## Instructions\" below as the mode's instructions."
    echo ""
    echo "**Name:** $name"
    echo "**Description:** $description"
    echo ""
    echo "## Instructions"
    echo ""
    # Full body, verbatim, unabridged — everything after the closing "---"
    # of the frontmatter (this includes the "## Essence" block and the
    # agent's own "# <Title>" heading — nothing is stripped or condensed).
    awk '/^---$/{n++; next} n>=2' "$src"
  } > "$out_file"

  echo "agent-to-mode.sh: $src -> $out_file"
}

if [ -d "$SRC" ]; then
  found=false
  for f in "$SRC"/*.md; do
    [ -f "$f" ] || continue
    found=true
    convert_one "$f" "$OUT_DIR"
  done
  if [ "$found" = false ]; then
    echo "agent-to-mode.sh: no *.md files found in $SRC" >&2
    exit 1
  fi
elif [ -f "$SRC" ]; then
  convert_one "$SRC" "$OUT_DIR"
else
  echo "agent-to-mode.sh: source not found: $SRC" >&2
  exit 1
fi
