#!/bin/bash

# ============================================================================
# tools/cursor/adapt/rule-to-mdc.sh — registry rule (.md) -> Cursor rule (.mdc)
# ============================================================================
# Generalizes the generate_cursor_rule() bash function documented in
# docs/RESTRUCTURE-2026-06.md ("Rules de Cursor" section) — that function no
# longer exists standalone in this repo, this is a fresh implementation of
# the same transform, per Fase 3 of docs/AI-SETUP-PLAN-v2.md:
#
#   - frontmatter `paths:` key   -> `globs:` (same value, unchanged)
#   - frontmatter `description:` -> taken from the first `# Heading` in the body
#   - frontmatter `alwaysApply:` -> always `false`
#   - body                       -> copied VERBATIM (minus the heading line),
#                                    never summarized/paraphrased
#
# No new dependencies — pure bash/grep/sed/awk, matching this repo's existing
# style (AI-SETUP-PLAN-v2.md section 3 point 2, section 7's rejection of
# gray-matter). Nothing generated by this script is committed to this repo —
# it is always rendered fresh into the TARGET repo by setup-repo.sh /
# tools/cursor/enable.sh, so it can never go stale the way the old hand
# maintained per-repo/.cursor/rules/*.mdc did.
#
# Usage:
#   rule-to-mdc.sh <registry-rule.md>          <output-dir>   # single file
#   rule-to-mdc.sh <dir-of-registry-rules>     <output-dir>   # all *.md in dir
#
# Example:
#   tools/cursor/adapt/rule-to-mdc.sh registry/rules .cursor/rules
# ============================================================================

set -e

usage() {
  echo "Usage: rule-to-mdc.sh <registry-rule.md-or-dir> <output-dir>" >&2
  exit 1
}

[ $# -eq 2 ] || usage

SRC="$1"
OUT_DIR="$2"

mkdir -p "$OUT_DIR"

convert_one() {
  local src="$1"
  local out_dir="$2"
  local name paths_line heading out_file

  name="$(basename "$src" .md)"
  out_file="$out_dir/$name.mdc"

  # Frontmatter is the block between the first two lines that are exactly "---".
  # `paths:` lives inside that block.
  paths_line="$(awk '/^---$/{n++; next} n==1' "$src" | grep '^paths:' | sed 's/^paths:[[:space:]]*//')"
  if [ -z "$paths_line" ]; then
    echo "rule-to-mdc.sh: no 'paths:' key found in frontmatter of $src" >&2
    exit 1
  fi

  # description: first "# Heading" line found after the closing "---".
  heading="$(awk '/^---$/{n++; next} n>=2 && /^# / {print; exit}' "$src" | sed 's/^# //')"
  if [ -z "$heading" ]; then
    echo "rule-to-mdc.sh: no '# Heading' found in body of $src" >&2
    exit 1
  fi

  {
    echo "---"
    echo "description: $heading"
    echo "globs: $paths_line"
    echo "alwaysApply: false"
    echo "---"
    # Body verbatim: everything after the closing "---", minus the one line
    # that exactly matches the heading we just extracted. Nothing else is
    # touched — no re-indentation, no whitespace trimming, no summarizing.
    awk -v heading="# $heading" '
      /^---$/ { n++; next }
      n>=2 {
        if (!done && $0 == heading) { done=1; next }
        print
      }
    ' "$src"
  } > "$out_file"

  echo "rule-to-mdc.sh: $src -> $out_file"
}

if [ -d "$SRC" ]; then
  found=false
  for f in "$SRC"/*.md; do
    [ -f "$f" ] || continue
    found=true
    convert_one "$f" "$OUT_DIR"
  done
  if [ "$found" = false ]; then
    echo "rule-to-mdc.sh: no *.md files found in $SRC" >&2
    exit 1
  fi
elif [ -f "$SRC" ]; then
  convert_one "$SRC" "$OUT_DIR"
else
  echo "rule-to-mdc.sh: source not found: $SRC" >&2
  exit 1
fi
